meta_product_name: "Audiophile"
meta_title: "Audiophile - Your webshop for audio equipment"
meta_description: "Offering the best audio equipment available on the market"
meta_image: "image-header.jpg" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
